name = "houduan"  # 替换为你的 Worker 名称
main = "worker.js"  # 指定入口文件
compatibility_date = "2024-03-24"  # 使用最新兼容日期

kv_namespaces = [
  { binding = "FORUM_POSTS", id = "44d574a8c3ae4d6bb5745b8665ead38f" },
  { binding = "ANNOUNCEMENT", id = "e190811c11cd4c22bbe5e4425ab3cd55" },
  { binding = "SUBMISSIONS", id = "c51d478a601349a2b53db213ed43dd83" }
]
