name = "houduan"  # 替换为你的 Worker 名称
main = "worker.js"  # 指定入口文件
compatibility_date = "2024-03-24"  # 使用最新兼容日期

# 绑定 KV 命名空间（如果已创建）
kv_namespaces = [
  { binding = "FORUM_POSTS", id = "your-kv-namespace-id" },
  { binding = "ANNOUNCEMENT", id = "another-kv-namespace-id" }
]
